/**
 * SilentScribe — Export Formatters
 * ============================================================================
 * 
 * Pure functions that convert transcript data into various export formats.
 * Each function takes a segments array and session metadata, and returns
 * a formatted string ready for file download.
 * 
 * No side effects, no dependencies beyond constants.js.
 * 
 * Supported formats:
 * - TXT: Plain text with timestamps and speaker labels
 * - SRT: SubRip subtitle format (importable into VLC, Premiere, etc.)
 * - JSON: Full structured data with metadata
 * - MD: Markdown with headers, speakers, and formatted timeline
 * 
 * @module export
 */

import { UI_CONFIG } from './constants.js';


// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Export transcript as plain text.
 * 
 * Format:
 *   SilentScribe — Meeting Transcript
 *   Date: June 24, 2026 2:30 PM
 *   Platform: Google Meet
 *   Duration: 00:45:12
 *   
 *   [00:00:05] Me: Hello everyone, let's get started.
 *   [00:00:12] Others: Sounds good, let me share my screen.
 * 
 * @param {Object[]} segments - Transcript segments with start, end, speaker, text.
 * @param {Object} session - Session metadata with startTime, platform, duration, speakerNames.
 * @returns {string} Formatted plain text transcript.
 */
export function exportTxt(segments, session) {
  const lines = [];

  // Header
  lines.push('SilentScribe — Meeting Transcript');
  lines.push(`Date: ${formatDate(session.startTime)}`);
  lines.push(`Platform: ${formatPlatformName(session.platform)}`);
  lines.push(`Duration: ${formatDuration(session.duration)}`);
  lines.push('');
  lines.push('─'.repeat(50));
  lines.push('');

  // Segments
  for (const segment of segments) {
    const time = formatTimeBracket(segment.start);
    const speaker = getSpeakerName(segment.speaker, session.speakerNames);
    const text = segment.text.trim();

    lines.push(`${time} ${speaker}: ${text}`);
  }

  lines.push('');
  lines.push('─'.repeat(50));
  lines.push('Generated by SilentScribe');

  return lines.join('\n');
}


/**
 * Export transcript as SRT (SubRip Subtitle) format.
 * 
 * SRT is the universal subtitle format supported by virtually every
 * video player and editor. Each subtitle entry has:
 * - Sequential number (starting from 1)
 * - Timestamp range in HH:MM:SS,mmm --> HH:MM:SS,mmm format
 * - Text content (with optional speaker label prefix)
 * 
 * Format:
 *   1
 *   00:00:05,000 --> 00:00:11,500
 *   [Me] Hello everyone, let's get started.
 *   
 *   2
 *   00:00:12,000 --> 00:01:44,000
 *   [Others] Sounds good, let me share my screen.
 * 
 * @param {Object[]} segments - Transcript segments.
 * @param {Object} session - Session metadata.
 * @returns {string} SRT formatted subtitle file content.
 */
export function exportSrt(segments, session) {
  const entries = [];

  for (let i = 0; i < segments.length; i++) {
    const segment = segments[i];
    const number = i + 1;
    const startTime = formatTimeSrt(segment.start);
    const endTime = formatTimeSrt(segment.end);
    const speaker = getSpeakerName(segment.speaker, session.speakerNames);
    const text = segment.text.trim();

    entries.push(`${number}\n${startTime} --> ${endTime}\n[${speaker}] ${text}`);
  }

  return entries.join('\n\n') + '\n';
}


/**
 * Export transcript as structured JSON.
 * 
 * Includes full session metadata, transcript segments with all fields,
 * and export metadata. Machine-readable format suitable for further
 * processing, analysis, or import into other tools.
 * 
 * @param {Object[]} segments - Transcript segments.
 * @param {Object} session - Session metadata.
 * @returns {string} Pretty-printed JSON string.
 */
export function exportJson(segments, session) {
  const output = {
    session: {
      id: session.id,
      platform: session.platform,
      startTime: session.startTime,
      endTime: session.endTime,
      duration: session.duration,
      micEnabled: session.micEnabled,
      speakerNames: session.speakerNames || {},
    },
    transcript: {
      segmentCount: segments.length,
      wordCount: segments.reduce((sum, s) => sum + countWords(s.text), 0),
      totalDuration: segments.length > 0
        ? segments[segments.length - 1].end - segments[0].start
        : 0,
      segments: segments.map((seg) => ({
        start: round(seg.start, 3),
        end: round(seg.end, 3),
        speaker: getSpeakerName(seg.speaker, session.speakerNames),
        speakerOriginal: seg.speaker,
        text: seg.text.trim(),
        confidence: seg.confidence != null ? round(seg.confidence, 4) : null,
      })),
    },
    exportedAt: new Date().toISOString(),
    version: '1.0.0',
    tool: 'SilentScribe',
  };

  return JSON.stringify(output, null, 2);
}


/**
 * Export transcript as Markdown.
 * 
 * Creates a well-formatted Markdown document with:
 * - Session metadata header
 * - Speaker legend (with custom names if set)
 * - Timestamped transcript with speaker labels in bold
 * 
 * Format:
 *   # Meeting Transcript
 *   
 *   **Date:** June 24, 2026 2:30 PM  
 *   **Platform:** Google Meet  
 *   **Duration:** 00:45:12
 *   
 *   ## Speakers
 *   - **Me** (Rahul)
 *   - **Others** (Priya)
 *   
 *   ## Transcript
 *   
 *   `00:00:05` **Me:** Hello everyone, let's get started.
 *   
 *   `00:00:12` **Others:** Sounds good, let me share my screen.
 * 
 * @param {Object[]} segments - Transcript segments.
 * @param {Object} session - Session metadata.
 * @returns {string} Markdown formatted transcript.
 */
export function exportMd(segments, session) {
  const lines = [];

  // Title
  lines.push('# Meeting Transcript');
  lines.push('');

  // Metadata
  lines.push(`**Date:** ${formatDate(session.startTime)}  `);
  lines.push(`**Platform:** ${formatPlatformName(session.platform)}  `);
  lines.push(`**Duration:** ${formatDuration(session.duration)}`);
  lines.push('');

  // Speaker legend
  const speakerNames = session.speakerNames || {};
  const uniqueSpeakers = [...new Set(segments.map((s) => s.speaker))];
  if (uniqueSpeakers.length > 0) {
    lines.push('## Speakers');
    lines.push('');
    for (const speaker of uniqueSpeakers) {
      const customName = speakerNames[speaker];
      if (customName && customName !== speaker) {
        lines.push(`- **${speaker}** _(${customName})_`);
      } else {
        lines.push(`- **${speaker}**`);
      }
    }
    lines.push('');
  }

  // Transcript
  lines.push('## Transcript');
  lines.push('');

  for (const segment of segments) {
    const time = formatTimeCompact(segment.start);
    const speaker = getSpeakerName(segment.speaker, session.speakerNames);
    const text = segment.text.trim();

    lines.push(`\`${time}\` **${speaker}:** ${text}`);
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(`_Generated by SilentScribe on ${formatDate(Date.now())}_`);

  return lines.join('\n');
}


// ============================================================================
// FORMATTING HELPERS
// ============================================================================

/**
 * Format a timestamp in seconds as [MM:SS].
 * Used for plain text export.
 * 
 * @param {number} seconds - Time in seconds.
 * @returns {string} Formatted as [MM:SS].
 */
function formatTimeBracket(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `[${pad(m)}:${pad(s)}]`;
}


/**
 * Format a timestamp in seconds as MM:SS.
 * Used for Markdown export (without brackets).
 * 
 * @param {number} seconds - Time in seconds.
 * @returns {string} Formatted as MM:SS.
 */
function formatTimeCompact(seconds) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${pad(m)}:${pad(s)}`;
}


/**
 * Format a timestamp in seconds as HH:MM:SS,mmm for SRT format.
 * 
 * SRT requires the specific format: HH:MM:SS,mmm where mmm is
 * milliseconds (3 digits). Uses comma as the decimal separator
 * (not period — that's the SRT standard).
 * 
 * @param {number} seconds - Time in seconds (may have decimals).
 * @returns {string} Formatted as HH:MM:SS,mmm.
 */
function formatTimeSrt(seconds) {
  const totalMs = Math.round(seconds * 1000);
  const h = Math.floor(totalMs / 3_600_000);
  const m = Math.floor((totalMs % 3_600_000) / 60_000);
  const s = Math.floor((totalMs % 60_000) / 1_000);
  const ms = totalMs % 1_000;

  return `${pad(h)}:${pad(m)}:${pad(s)},${padMs(ms)}`;
}


/**
 * Format a duration in milliseconds as HH:MM:SS.
 * 
 * @param {number} ms - Duration in milliseconds.
 * @returns {string} Formatted as HH:MM:SS.
 */
function formatDuration(ms) {
  if (!ms || ms <= 0) return '00:00:00';

  const totalSeconds = Math.floor(ms / 1000);
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;

  return `${pad(h)}:${pad(m)}:${pad(s)}`;
}


/**
 * Format a Unix timestamp as a human-readable date string.
 * 
 * @param {number} timestamp - Unix timestamp in milliseconds.
 * @returns {string} E.g., "June 24, 2026 2:30 PM".
 */
function formatDate(timestamp) {
  if (!timestamp) return 'Unknown date';

  return new Date(timestamp).toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
}


/**
 * Format a platform identifier as a human-readable name.
 * 
 * @param {string} platform - Platform identifier (e.g., 'google-meet').
 * @returns {string} Human-readable name (e.g., 'Google Meet').
 */
function formatPlatformName(platform) {
  const names = {
    'google-meet': 'Google Meet',
    'zoom': 'Zoom',
    'teams': 'Microsoft Teams',
    'webex': 'Cisco Webex',
    'unknown': 'Unknown Platform',
  };
  return names[platform] || platform || 'Unknown Platform';
}


/**
 * Get the display name for a speaker, applying user-defined overrides.
 * 
 * Users can rename speakers post-recording (e.g., "Me" → "Rahul").
 * This function applies those overrides, falling back to the original
 * label if no override exists.
 * 
 * @param {string} speaker - Original speaker label ('Me' or 'Others').
 * @param {Object} speakerNames - Map of original label → custom name.
 * @returns {string} The display name for the speaker.
 */
function getSpeakerName(speaker, speakerNames) {
  if (speakerNames && speakerNames[speaker]) {
    return speakerNames[speaker];
  }
  return speaker || UI_CONFIG.DEFAULT_SPEAKERS.OTHERS;
}


// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Pad a number to 2 digits with leading zero.
 * 
 * @param {number} n - Number to pad.
 * @returns {string} Zero-padded string.
 */
function pad(n) {
  return String(n).padStart(2, '0');
}


/**
 * Pad milliseconds to 3 digits with leading zeros.
 * 
 * @param {number} n - Milliseconds (0-999).
 * @returns {string} Zero-padded string.
 */
function padMs(n) {
  return String(n).padStart(3, '0');
}


/**
 * Count words in a text string.
 * 
 * @param {string} text - Input text.
 * @returns {number} Word count.
 */
function countWords(text) {
  if (!text || !text.trim()) return 0;
  return text.trim().split(/\s+/).length;
}


/**
 * Round a number to a specified number of decimal places.
 * 
 * @param {number} value - Number to round.
 * @param {number} decimals - Number of decimal places.
 * @returns {number} Rounded number.
 */
function round(value, decimals) {
  return Number(Math.round(value + 'e' + decimals) + 'e-' + decimals);
}
